sheets/ncmpcpp

mostly taken from https://pkgbuild.com/~jelle/ncmpcpp/

ncmpcpp cheat sheet

---

sheets/cloudup
sheets/crypt
sheets/currency
sheets/geo
sheets/movies
sheets/qrify
sheets/short
sheets/siteciphers
sheets/stocks
sheets/taste
sheets/todo
sheets/weather
sheets/ytview

Didnt add cheat as i thought that was a little recursive

Adding bash-snippets tools

---

sheets/_c++/arrays
sheets/_c++/class
sheets/_c++/func
sheets/_c++/hello
sheets/_c++/if
sheets/_c++/loops
sheets/_c++/pointers
sheets/_c++/struct
sheets/_c++/structs
sheets/_c++/types
sheets/_c++/vector
sheets/_python/func
sheets/_python/loops
sheets/c++

This is just a start. Please let me know if I'm missing something. I can add more over the course of the week! 
I'll submit a new cheat sheet tonight to chubin/cheat.sh.

Started addition of C++ sheet & some python topics

---

sheets/_python/lambda
sheets/_python/recursion
sheets/recursion

Let me know if there are any errors. 
Cheers, 
Patrick

Python Recursion and Python Lambda

---

sheets/bash

First contribution to this. Added a few Bash cheats.

Bash additions

---

sheets/curl

Adding command example of downloading a file and following 301 redirects.

Update curl cheat sheet with redirect

---

sheets/_scala/ControlStructures
sheets/_scala/DataStructures
sheets/_scala/Functions
sheets/_scala/Options
sheets/_scala/PatternMatching
sheets/_scala/Variables

As a Scala user, I felt the Scala documentation could use a few improvements.
There is probably a lot more that can be added to those sheets but I started by trying to improve on what already exists and add a little more of the fundamentals where I could.

Added to the Scala sheets

---

sheets/say

I find this very useful for picking the voice. Hope it helps someone else!

Added spoken voice list to Say sheet

---

sheets/ocaml

I do not know why this reference to Perl5, maybe a typo?

Remove reference to Perl5

---

sheets/_js/hello

Hey, I fixed a small typo in the hello file for JS.

Fix typo in js/hello

---

sheets/_python/loops

'for else' fix

---

sheets/_swift/types

Added cheatsheet for swift types.

swift types

---

sheets/bash

additional redirection tricks
convert spaces to underscores
named pipes for colorizing tail of multiple files

Adding additional usefuls

---

sheets/ccze

added first cheat for ccze using named pipes to colorize multiple files at once while tailing them in the shell

New sheet: ccze for colorizing logs

---

sheets/lvextend

Hello, I would like to add a lvextend sheet, since I need to do that now and then, and I never can remember which fs extend command one has to use for which file system.

Added lvextend sheet.

---

sheets/tmate

Provide all the core usage examples from tmate.io

Create tmate cheatsheet

---

sheets/rhash

been using rhash last few days and kept wishing for a cheatsheet

adding initial rhash cheatsheet

---

sheets/dar

A simple cheat sheet consisting of the bare
minimum needed to use dar. Dars HOWTO
has many examples of complex usage, but
none on the most basic use cases.

add cheat sheet for dar

---

sheets/ssh

Most useful for terminating unresponsive sessions

ssh: add info about escape sequences

---

sheets/git

Just adds a cheat entry for `git branch -a` to list all remote and local branches.

 updated git - added branch cheat

---

sheets/_ruby/control_flow

No need to add extra lines to the output. Shorter is better :)

[ruby] merge if/else with if/elsif/else

---

sheets/_emacs/_info.yaml
sheets/_emacs/dired
sheets/_emacs/macros
sheets/_emacs/telnet
sheets/emacs

Some changes related to #75 
What do you think?

[emacs] move some info to separate files

---

sheets/_ruby/case

A bit advanced but required knowledge about the magic in `case`

[ruby][case] Add a note about ===

---

sheets/ruby

Quite a useful switch for one-liners

add note on ruby -l switch

---

sheets/proc

Feel like there's good use. There's a `man proc` so this can do that as well.

sheet for /proc pseudo-directory

---

sheets/awk
sheets/find
sheets/stat

Hope these help someone as much as the knowledge thereof has helped me over the years.
Might as well keep the PR open, as I'd like to keep pushing more. I have thousands of real corkers, from standard to advanced in a shell notes file of over 5000 lines. Good times.
This is a very cool repository idea, by the way.
I actually wrote a [small program](https://github.com/terminalforlife/Extra/blob/master/snotes) which parses my notes file, so I can quickly view them, based on matches. You might find it interesting, as it would go well with a compiled version of all of these. On that note, I imagine something to parse all of these "cheat sheets", for easy searching, could be handy.

A Few Additional Code Lines (Likely More to Come)

---

sheets/convert
sheets/find
sheets/nl
sheets/sed
sheets/xargs

Having some fun doing this. :P

Additional New Entries, Counters, and Files

---

sheets/_bash/forkbomb
sheets/apt-cache
sheets/apt-get
sheets/dpkg-deb
sheets/source
sheets/udisksctl
sheets/umask

More Goodies

---

sheets/awk
sheets/bash
sheets/dpkg-deb
sheets/lvcreate
sheets/xev

See the commit messages, if any, for info. Hope they help.

More of the Same

---

sheets/i3

See #85
Added most useful i3 hotkeys and quick guide about precise window positioning with containers.

Added i3 cheatsheet

---

sheets/aspell
sheets/awk
sheets/bash
sheets/xev

Tweaks & AWK Addition

---

sheets/git
sheets/perl
sheets/ssh
sheets/sysctl
sheets/tee

Hope these help. If there's anything at all I can do here, please let me know. I love this repository!

New Examples & `sysctl` File + Wording & Formatting Improvements

---

sheets/sed

Sed's cheat sheet was a little light, here are a few more examples.

Adding a few more useful examples to sed.

---

sheets/emacs

Just fixing some minor typos on emacs file.

emacs: fix typos

---

sheets/tee

Newline for formatting.
Author meant append, not amend - amend means to edit, append means to add to.

Append, not amend.

---

sheets/_perl/1line
sheets/apt-get
sheets/apt-key
sheets/cat
sheets/dpkg
sheets/perl
sheets/perldoc
sheets/printf
sheets/proc
sheets/wget

Hope these help.
I really love this project, and often recommend it to people. :)

Added Files & Examples

---

sheets/colrm
sheets/dd
sheets/df
sheets/printf
sheets/source
sheets/ss
sheets/ssh
sheets/stat
sheets/sudo
sheets/wget
sheets/xset

I'm trying to make the files as consistent as possible, so that parsing is reliable, readability is improved, and the sheets are presentable.
I mentioned some of my goals/thoughts within [this](https://youtu.be/Ly5QORi7qCY) YouTube video. Also just a bit of a shout-out to the project, because clearly I'm a bit of a fan. :P

Wording, Formatting, & Entries

---

sheets/doas

Add a "doas" entry to the sheets

Add "doas" file

---

sheets/airport
sheets/apk
sheets/apt-cache
sheets/apt-get
sheets/apt-key
sheets/aspell
sheets/awk
sheets/aws
sheets/az
sheets/bash
sheets/fdisk
sheets/find
sheets/go
sheets/js
sheets/libreoffice
sheets/lua
sheets/lynx
sheets/mutt
sheets/nl
sheets/nodejs
sheets/xargs
sheets/xev
sheets/xsel

Hope these commits help. Let me know if there are any issues.

Code, Formatting Tweaks, Some Fixes, Headers, etc

---

sheets/exim

Some (wonder if not too many) examples of managing exim queue

New cheat sheet: exim

---

sheets/_rust/Cargo

- New comment style avoids incorrect syntax highlighting

Tweak comments in Cargo sheet, add more frequently used commands

---

sheets/i3

Shortcuts for reloading config file, restart `i3` and exit `i3`

Adding 3 basic shortcuts for i3

---

sheets/chmod
sheets/curl
sheets/df
sheets/dict
sheets/dmesg
sheets/htop
sheets/look
sheets/lshw
sheets/proc
sheets/pup
sheets/ruby
sheets/say
sheets/scrot
sheets/xset

BTW, it looks like `convert` needs header stuff added, but I haven't a way to access that. If anyone's gonna take that up, I tend to get the short description from the man page or package information; whichever's relevant.

More Mostly-Presentational Tweaks

---

sheets/python

fix: missed space in python

---

sheets/heaptrack

Just a quick tweak to the presentation of the recent PR: #122

Slight Presentation Tweak

---

sheets/ch-run

Thanks for all your helps @terminalforlife. Please check this one too. <img src="https://cdn.discordapp.com/emojis/451143444753154058.gif" height=24 alt="ameowattention">

add another example to ch-run

---

tests/lenchk

Addressed changes suggested by @chubin in #133 PR. Refer to commit messages if I missed anything. Hope you like it. :D I took a little *too* long working on this. Lol I did add a few extra features.

Add Changes Mentioned in #133

---

sheets/dpkg-deb
sheets/system_profiler
tests/lenchk

Improve `lenchk` and Fix Some Line Lengths

---

sheets/yq

Added a sheet for ya, the [YAML processing tool](https://github.com/mikefarah/yq).

Add yq sheet

---

sheets/yq
sheets/yq_v4

I added the yq_v4 for version 4. When v4 becomes stable, we could flip them and make v4 the default.

Add yq_v4 sheet for yq version 4

---

sheets/_scala/Functions
sheets/mount
sheets/perl

~~Just one, for the sake of a YouTube video. Lol~~ (was rubbish; will probably re-record tomorrow)
Some line length fixing and new sheet stuff.

Line Length Fixes & New Sheet Stuff

---

sheets/MegaCli
sheets/az
sheets/azure
sheets/blktrace
sheets/emacs
sheets/exim
sheets/go
sheets/ipython
sheets/jq
sheets/nmap
sheets/perl
sheets/psql
sheets/redis
sheets/sed
sheets/smartctl
sheets/solidity
sheets/yq_v4

*  sheets/MegaCli
*  sheets/az
*  sheets/azure
*  sheets/blktrace
*  sheets/emacs
*  sheets/exim
*  sheets/go
*  sheets/ipython
*  sheets/jq
*  sheets/nmap
*  sheets/perl
*  sheets/psql
*  sheets/redis
*  sheets/sed
*  sheets/smartctl
*  sheets/solidity
*  sheets/yq_v4

Fix comment length in all first-level cheat sheets

---

sheets/tsp

This PR introduces a cheat sheet for the task-spooler program (http://manpages.ubuntu.com/manpages/xenial/man1/tsp.1.html).

Create task-spooler sheet

---

sheets/_bash/shortcuts

Create a cheat sheet describing bash interactive keyboard shortcuts

Add bash keyboard shortcuts cheat sheet

---

sheets/nvidia-settings

Please refer to the commit messages, if there are any.
Happy belated Xmas and New Year, BTW. :)

Reticulated Splines for the Flux Capacitor's Vega Sequencer

---

sheets/glkfu

Added GLKFU Cheat Sheet

---

sheets/postgresql

Some additional postgres commands that would find useful
Being able to run the `psql` with the `-c` flag for a one liner
Being able to spin up a postgres docker container rather than installing it locally

Additional postgres commands

---

sheets/xinput

Just discovered this today; is awesome.

New Cheat Sheet

---

sheets/lse

I've added a script that I often need to refer to my own notes for :
This is the linux-smart-enumeration, or lse script, based on enum4linux.

Added lse (Linux-Smart-Enumeration) script

---

sheets/find

Sorry for being a small commit, this was for the benefit of YouTube, to hopefully inspire people to contribute to this awesome project. :)
This is the video @chubin:
https://www.youtube.com/watch?v=ZJ3lPQVoiVw
If I got anything wrong, or you want to address viewers there, please feel free to leave a comment and I'll gladly pin it.

Note find(1)'s recursivity & use of `.` for CWD

---

sheets/_js/weirdness

In javascript there error about calculation on decimal numbers. I  was add one of them.

Add to weirdness

---

sheets/iscsiadm

bcs i forget about the syntax each time i have to use it.

add cheat sheet for iscsiadm

---

sheets/apt-config
sheets/awk
sheets/pactl

Cannot believe I didn't know about AWK sorting, even after all these years!

Add Awesome AWK Example & Other Useful Stuff

---

sheets/sqlcmd

Introduce [sqlcmd](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15) utility

Add sqlcmd sheet

---

sheets/bash
sheets/xattr
sheets/xm
sheets/xscreensaver
sheets/yay

Please refer to the commit messages for any further information.
This is also to address #172.

Some Parameter Expansion Stuff for BASH & Some Tidying

---

sheets/awk

Added: 
- basic Awk commands,
- one-liner for removing duplicates,
- one-liner for removing empty lines.

Update Awk cheat sheet

---

sheets/spring

Initialize Spring

---

sheets/cleancss
sheets/deno fmt
sheets/eslint
sheets/husky
sheets/js-beautify
sheets/jscs
sheets/jshint
sheets/prettier
sheets/standard
sheets/stylelint
sheets/tslint
sheets/xo
topics/javascript-code-formatting-and-linting.json

| **Command**   | **Command Description**                                                          |
|---------------|----------------------------------------------------------------------------------|
| `aliyun-code` | Manage and deploy code to Alibaba Cloud services.                                |
| `babel-eslint`| Lint JavaScript code using ESLint with Babel parsing support.                    |
| `cleancss`    | Minify and optimize CSS files.                                                   |
| `deno fmt`    | Format Deno code using the built-in formatter.                                   |
| `eslint`      | Pluggable linting utility for JavaScript and JSX.                                |
| `eslint-config-airbnb`| Shareable ESLint configuration for Airbnb's JavaScript style …

Add JavaScript code formatting/linting tools cheat sheets
